plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yuelan.bb9'
    compileSdk 35

    defaultConfig {
        applicationId 'com.yuelan.bb9'
        minSdk 24
        targetSdk 35
        versionCode 241
        versionName '2.4.1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies { }
